import { Notice, ClubEvent, LibraryFolder, LibraryFile, Channel, ChatMessage } from './types';

export const INITIAL_NOTICES: Notice[] = [
  {
    id: 'n1',
    title: 'Lab 4 Maintenance',
    content: 'Computer Lab 4 will be closed this afternoon for software updates. Please use Lab 2 for project work.',
    author: 'Admin',
    time: '2 hours ago',
    category: 'blue',
  },
  {
    id: 'n2',
    title: 'Google Cloud Credits',
    content: 'Check the resource hub for a link to claim your student GCP credits. Valid for all IT/CS students.',
    author: 'Dev Lead',
    time: 'Yesterday',
    category: 'emerald',
  },
  {
    id: 'n3',
    title: 'New Committee Members',
    content: 'Welcome to our new event coordinators for the 2026 academic year. Read their intro post to learn about planned activities.',
    author: 'Chairman',
    time: 'Mon',
    category: 'purple',
  },
];

export const INITIAL_EVENTS: ClubEvent[] = [
  {
    id: 'e1',
    title: "Annual Hackathon '26",
    date: 'Friday, 15th July',
    location: 'Main Campus Hall',
    category: 'Upcoming Event',
    details: 'A 24-hour coding challenge for developers, designers, and innovators to build impactful campus solutions. Prizes worth over $1,500 up for grabs!',
    teamRegistered: false,
  },
];

export const INITIAL_FOLDERS: LibraryFolder[] = [
  { id: 'f1', name: 'Web Development', itemsCount: 42 },
  { id: 'f2', name: 'Mobile Apps', itemsCount: 28 },
  { id: 'f3', name: 'AI & Data Science', itemsCount: 15 },
  { id: 'f4', name: 'Past Papers', itemsCount: 104 },
];

export const INITIAL_FILES: LibraryFile[] = [
  {
    id: 'file1',
    name: 'React_Hooks_Cheatsheet.pdf',
    size: '2.4 MB',
    type: 'pdf',
    uploader: 'Sarah T.',
    time: '2 hrs ago',
    category: 'Web Development',
  },
  {
    id: 'file2',
    name: 'Figma UI Kit - Club Assets 2026',
    size: 'External Link',
    type: 'link',
    uploader: 'UX Lead',
    time: 'Yesterday',
    category: 'Web Development',
  },
  {
    id: 'file3',
    name: 'Express_Server_Boilerplate.zip',
    size: '15 KB',
    type: 'zip',
    uploader: 'Dev Team',
    time: 'Mon',
    category: 'Web Development',
  },
  {
    id: 'file4',
    name: 'Intro_to_Python_DataScience.pdf',
    size: '4.1 MB',
    type: 'pdf',
    uploader: 'Prof. J. Ndegwa',
    time: 'Last Week',
    category: 'AI & Data Science',
  },
  {
    id: 'file5',
    name: 'BIT_3104_DatabaseSystems_PastPaper_2025.pdf',
    size: '1.2 MB',
    type: 'pdf',
    uploader: 'Admin',
    time: '2 weeks ago',
    category: 'Past Papers',
  },
];

export const INITIAL_CHANNELS: Channel[] = [
  // Community Group Channels
  { id: 'general', name: 'general', description: 'General announcements and friendly banter', unreadCount: 3, isDM: false },
  { id: 'help-frontend', name: 'help-frontend', description: 'Ask questions and debug CSS, HTML, React, etc.', unreadCount: 0, isDM: false },
  { id: 'opportunities', name: 'opportunities', description: 'Jobs, internships, hackathons, and scholarship listings', unreadCount: 0, isDM: false },
  { id: 'web-dev-syllabus', name: 'web-dev-syllabus', description: 'Discuss the 10-Part Zero-to-Expert Web Dev Curriculum & get code help', unreadCount: 5, isDM: false },
  
  // Direct Messages (DMs)
  {
    id: 'dm-ai-tutor',
    name: 'Gemini AI Tutor ⚡',
    description: 'Instant answers for the 10-Part Web Dev Course',
    unreadCount: 1,
    isDM: true,
    avatarUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150',
    online: true,
    statusText: '24/7 Course Assistant | Trained on tutorial.json',
    regNumber: 'AI/2026/GEMINI',
  },
  {
    id: 'dm-sarah',
    name: 'Sarah T. (UX Lead)',
    description: 'Typing...',
    unreadCount: 1,
    isDM: true,
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    online: true,
    statusText: 'Designing the future ✨ | Figma expert',
    regNumber: 'BIT/2024/4921',
  },
  {
    id: 'dm-mike',
    name: 'Mike O. (Fullstack)',
    description: 'Let me look at the React boilerplate...',
    unreadCount: 0,
    isDM: true,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    online: true,
    statusText: 'TypeScript and Node.js geek 🚀',
    regNumber: 'BCS/2025/1102',
  },
  {
    id: 'dm-ndegwa',
    name: 'Prof. J. Ndegwa (Patron)',
    description: 'Keep up the good work on the hackathon.',
    unreadCount: 0,
    isDM: true,
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    online: false,
    statusText: 'MKU IT Department Patron | Research Advisor',
    regNumber: 'FACULTY-IT-02',
  },
  {
    id: 'dm-chairman',
    name: 'Dave (Club Chairman)',
    description: 'We need to submit the budget by 5 PM.',
    unreadCount: 0,
    isDM: true,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    online: true,
    statusText: 'Leading with Purpose | MKU IT Chairman 2026 🎓',
    regNumber: 'BIT/2023/8812',
  },
];

export const INITIAL_CHAT_HISTORY: Record<string, ChatMessage[]> = {
  general: [
    {
      id: 'm1',
      channelId: 'general',
      sender: 'Sarah T.',
      time: '10:40 AM',
      text: "Hey everyone! Does anyone have the notes from yesterday's intro to React meeting? I had to leave early.",
      self: false,
    },
    {
      id: 'm2',
      channelId: 'general',
      sender: 'Mike O.',
      time: '10:42 AM',
      text: "Yeah, I uploaded them to the Resources tab under Web Dev. Here's a quick link though.",
      self: false,
    },
    {
      id: 'm3',
      channelId: 'general',
      sender: 'Alex M.',
      time: '10:45 AM',
      text: 'Thanks Mike! Super helpful. Will review these before the weekend hackathon.',
      self: true,
      status: 'read',
    },
  ],
  'help-frontend': [
    {
      id: 'm4',
      channelId: 'help-frontend',
      sender: 'Alex M.',
      time: 'Yesterday 3:15 PM',
      text: 'Does anyone know how to handle absolute positioning inside a flex layout?',
      self: true,
      status: 'read',
    },
    {
      id: 'm5',
      channelId: 'help-frontend',
      sender: 'Mike O.',
      time: 'Yesterday 3:18 PM',
      text: 'Wrap the item in a relative div container so the absolute positioning is scoped to that element!',
      self: false,
    },
    {
      id: 'm6',
      channelId: 'help-frontend',
      sender: 'Alex M.',
      time: 'Yesterday 3:30 PM',
      text: 'I managed to fix the flexbox issue. Thanks!',
      self: true,
      status: 'read',
    },
  ],
  opportunities: [
    {
      id: 'm7',
      channelId: 'opportunities',
      sender: 'Admin',
      time: 'Mon 9:00 AM',
      text: 'Google DSC is looking for lead application candidates. Check out the student dashboard!',
      self: false,
    },
    {
      id: 'm8',
      channelId: 'opportunities',
      sender: 'Admin',
      time: 'Mon 2:15 PM',
      text: 'New internship postings available from Safaricom. Apply using your student email.',
      self: false,
    },
  ],
  'web-dev-syllabus': [
    {
      id: 'ws1',
      channelId: 'web-dev-syllabus',
      sender: 'Prof. J. Ndegwa (Patron)',
      time: '08:00 AM',
      text: "Welcome to the official discussion channel for 'The Complete Zero-to-Expert HTML, CSS, and JavaScript Unified Course' (tutorial.json)! All 10 Parts and 100+ interactive labs are now live in the Resources tab and IDE Playground.",
      self: false,
    },
    {
      id: 'ws2',
      channelId: 'web-dev-syllabus',
      sender: 'Sarah T.',
      time: '09:15 AM',
      text: "Just completed Chapter 3.1 on Semantic HTML5! The difference between <article> and <section> makes so much sense now. You can try the starter card template right in the editor!",
      self: false,
    },
    {
      id: 'ws3',
      channelId: 'web-dev-syllabus',
      sender: 'Mike O.',
      time: '09:30 AM',
      text: "The CSS Grid Bento layout in Part 5 is 🔥. Make sure to click 'Mark Mastered' in the Library view to earn your +25 XP rewards!",
      self: false,
    },
  ],
  // DM Histories
  'dm-ai-tutor': [
    {
      id: 'ai1',
      channelId: 'dm-ai-tutor',
      sender: 'Gemini AI Tutor ⚡',
      time: 'Now',
      text: "Hello Alex! I am your interactive AI Course Tutor for Mount Kenya University's IT Club. Ask me anything about our 10-part syllabus (HTML5, CSS Grid, DOM Manipulation, LocalStorage, or Capstone Projects), or ask me to explain any code snippet from the tutorial!",
      self: false,
    },
  ],
  'dm-sarah': [
    {
      id: 'dm1_1',
      channelId: 'dm-sarah',
      sender: 'Sarah T. (UX Lead)',
      time: 'Yesterday 4:20 PM',
      text: 'Hey Alex! Did you manage to test the prototype of the new club App UI?',
      self: false,
    },
    {
      id: 'dm1_2',
      channelId: 'dm-sarah',
      sender: 'Alex M.',
      time: 'Yesterday 4:22 PM',
      text: 'Yes! It looks outstanding. The colors are very professional, especially the Android drawer and navigation details.',
      self: true,
      status: 'read',
    },
    {
      id: 'dm1_3',
      channelId: 'dm-sarah',
      sender: 'Sarah T. (UX Lead)',
      time: 'Yesterday 4:25 PM',
      text: 'Awesome, thanks! I am working on the chat system right now. Want it to look exactly like WhatsApp!',
      self: false,
    },
    {
      id: 'dm1_4',
      channelId: 'dm-sarah',
      sender: 'Sarah T. (UX Lead)',
      time: '09:12 AM',
      text: 'Can we sync today to finalize the Hackathon registration page?',
      self: false,
    },
  ],
  'dm-mike': [
    {
      id: 'dm2_1',
      channelId: 'dm-mike',
      sender: 'Mike O. (Fullstack)',
      time: 'Tuesday 2:00 PM',
      text: 'Hey man, are you using the @google/genai SDK for the AI features?',
      self: false,
    },
    {
      id: 'dm2_2',
      channelId: 'dm-mike',
      sender: 'Alex M.',
      time: 'Tuesday 2:02 PM',
      text: 'Yes, initialized on the server side with process.env.GEMINI_API_KEY. It prevents exposing keys in the browser.',
      self: true,
      status: 'read',
    },
    {
      id: 'dm2_3',
      channelId: 'dm-mike',
      sender: 'Mike O. (Fullstack)',
      time: 'Tuesday 2:05 PM',
      text: 'Perfect! Let me look at the React boilerplate code on GitHub so we can merge it.',
      self: false,
    },
  ],
  'dm-ndegwa': [
    {
      id: 'dm3_1',
      channelId: 'dm-ndegwa',
      sender: 'Prof. J. Ndegwa (Patron)',
      time: 'Wednesday 11:30 AM',
      text: 'Alex, please ensure all participating students are verified members for the upcoming Hackathon.',
      self: false,
    },
    {
      id: 'dm3_2',
      channelId: 'dm-ndegwa',
      sender: 'Alex M.',
      time: 'Wednesday 11:35 AM',
      text: 'Will do, Professor. We have set up a verified student badge system in their event profiles.',
      self: true,
      status: 'read',
    },
    {
      id: 'dm3_3',
      channelId: 'dm-ndegwa',
      sender: 'Prof. J. Ndegwa (Patron)',
      time: 'Wednesday 11:40 AM',
      text: 'Excellent. Keep up the good work on the hackathon.',
      self: false,
    },
  ],
  'dm-chairman': [
    {
      id: 'dm4_1',
      channelId: 'dm-chairman',
      sender: 'Dave (Club Chairman)',
      time: '10:00 AM',
      text: 'Hey Alex, do we have the final count of teams registered for the event?',
      self: false,
    },
    {
      id: 'dm4_2',
      channelId: 'dm-chairman',
      sender: 'Alex M.',
      time: '10:05 AM',
      text: 'Yes, we have 12 teams fully registered so far! I will export the spreadsheet from our system now.',
      self: true,
      status: 'read',
    },
    {
      id: 'dm4_3',
      channelId: 'dm-chairman',
      sender: 'Dave (Club Chairman)',
      time: '10:06 AM',
      text: 'Brilliant! Also, we need to submit the budget by 5 PM. Can you double check the lab maintenance expenses list?',
      self: false,
    },
  ],
};
